### ISSUE TITLE
Corp Theme

### ISSUE THREAD

**Issue by johntom** [oncletom/hexo-algolia#12]
Hi,
Trying to add hexo-algolia to https://github.com/ptsteadman/hexo-theme-corporate-example and when I run hexo algolia I get following error

```
  C:\Nodejs\hexo-theme-corporate-example>hexo algolia
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'fields' of undefined
    at Hexo.algolia (C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo-algoliasearch\lib\algolia.js:16:39)
    at Hexo.tryCatcher (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at <anonymous> (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo\lib\hexo\index.js:192:9
    at Promise._execute (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\promise.js:77:14)
    at Hexo.call (C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo\lib\hexo\index.js:188:10)
    at C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\hexo-cli\lib\hexo.js:63:17
    at tryCatcher (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
FATAL Cannot read property 'fields' of undefined
TypeError: Cannot read property 'fields' of undefined
    at Hexo.algolia (C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo-algoliasearch\lib\algolia.js:16:39)
    at Hexo.tryCatcher (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at <anonymous> (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo\lib\hexo\index.js:192:9
    at Promise._execute (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Nodejs\hexo-theme-corporate-example\node_modules\bluebird\js\release\promise.js:77:14)
    at Hexo.call (C:\Nodejs\hexo-theme-corporate-example\node_modules\hexo\lib\hexo\index.js:188:10)
    at C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\hexo-cli\lib\hexo.js:63:17
    at tryCatcher (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Users\john\AppData\Roaming\npm\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by thom4parisot** [comment]
It looks like it had been an issue with the data being indexed.

Comment on this issue to reopen it again if the problem is still happening with the new 1.0.1 release 👍
